#!/usr/bin/zsh
if command -v code >/dev/null 2>&1; then
  code_extensions=$(cat "$HOME/dotfiles/code-extensions" | sort)
  installed_extensions=$(code --list-extensions | sort)
  incoming_extensions=$(comm -23 <(echo "$code_extensions") <(echo "$installed_extensions"))

  echo "Checking for incoming VSCode extensions..."

  if [ -z "$incoming_extensions" ]; then
    echo "All good!"
  else
    echo "Found $(echo "$incoming_extensions" | wc -l)."

    echo "$incoming_extensions" | while read -r extension; do
      echo "Installing $extension..."
      code --install-extension "$extension"
    done

    echo "Done!"
  fi
fi
